# Generated by Django 4.2.7 on 2023-11-30 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widiarti', '0002_alter_kategori_options_alter_kontak_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontak',
            old_name='no_whatsup',
            new_name='no_whatsApp',
        ),
    ]
