# Generated by Django 4.2.6 on 2024-01-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widiarti', '0004_chatid_alter_produk_gambar_alter_produk_gambar_dua_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatid',
            options={'verbose_name_plural': 'Data Chat ID'},
        ),
        migrations.AddField(
            model_name='produk',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
